using System;

namespace Hisenberg;

class Walt
{
    public static void WaltIMG()
    {
        object Walt = @"
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMWNX0Okxdoollcc::;;,;;;;;::::::;;,,,,;;:o0WWWMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMNx,..                                    ;KMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMk.                                        lNMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMNl                                         .kWMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMM0'                                          ,0MMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMWo                                            cXMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMO'                                            .xWMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMNl                                              :XWMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMO'                                              .dWWMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMWNXXWMMMMMMWd.                                               'OMMMMMMMNXXNWMMMMMMMMMWWMM
        MMWWMMMMMMWKo,.':oxkkOko'                                                 'ldkkOko;..:0WMMMMMMMMWWMM
        MMWWMMMMMMK:                                                                          cXMMMMMMMMWWMM
        MMWWMMMMMMW0dlc;''.....                                           ......            ..oNMMMMMMMMWWMM
        MMWWMMMMMMMMMMWWNNXK00O:.cOOOkkkxxddollcccc::;:cllllllooodxxxxxxxO0KKKK0l..cxxkkkkkO0XWMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMNc,0MMMMMMMMMMMMWNXXKKXXXXXXXXKKKKKKKKXXNWMMMMMMMMk..OMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMXc:XMMMMMMMMMMMMWX00000000O00000KK00000KXWMMMMMMMMO.'0WMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMXc;KMWMMMMMMWNNNNNNXXXKK00O00000000O0KKXXWMMMMMMMWx.,KMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMWd,kNNNNNWWWWWWWWWNNNXXXKXXXXXXXXKKKXXNXXXK00OOkkk: .kMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMWO:..''',,;;,;::::ccllloollllllllcc::;,'.....         oWMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMX:                        .,:;'.                     .xMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMWd.                     'lxNWW0d,                    ,KMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMX:                    'dOXWWWN0k,                  .oWMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMO.                  'O00WWWWW0Ox.                 ;KMMMWWMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMWd.                'kWKKMMWWW0kXo.               .xWMMMWMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMNd.              'kWWKXMMMWMKxKXc             ..cXMMMWWMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMNc...........';o0WMN0XMWMMMNxOWXd;.        .:xoxWMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMM0lxKKKXXXXXXNWWWWX00NMWWMMWXK0XWNKkdooloxOKNOo0MMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMNxoXMMMMMMMMMMWNOxOXNWMMWWWNXkdONMMMWMMMMWMXdOWMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMWWMXodXMMMMMMWMMNKKKO000KXXKO0XXKO0WWWMMMMMMXdxNMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMWWMMKlc0WWXXX0XX0odkk0KOxkxxxO00kxxOKKXMWWMWxoXMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMWMMWM0:,kN00kkOxo::cccllldxdlclooc:;dk0XKNWXx0MMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMK:cKXXkxOkocoolddddxkdllodoloodkO0KWNk0WMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMXdxNNO0N0O0K0kO00OOOkxxkkkkxOXN0KWNxxNMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxdKO0N0KWNKKKKK000000KKKXKXNW0KNkkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdokOXWWWWWMWMMMMMMMMMMMMMMMN00kkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNdlONMMMMMMMMMMMMMMMMMMMMMWW0dONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWXxo0WMMMMMMMMMMMMMWWMMMMWWKdkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWW0xxkO0XWMWWMMMMMWWNNK0Okk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWMWX0kxxkkxxkOOOOO00000XNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOkkk0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMNWMWNWNK0KXNWNKKNMWX0KWMNKKKXWNXXWMWWWXKKXWWXKKKXWNKKKNWMNK0XMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMXxOWXx0klxO0NW0coNWklx0NNdlkOKNk::xNOO0ookoxXdlkOKNxlkddK0oxkONMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMXccko:kk:dO0XMNdxWWKxxOXNo:kO0Nx';lxdx0clk:oXo:OOKNo:dlo0doXXKXWMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMXloKx:kklOXXWMXoxWWWNKddKolKXXNx,d0l'o0ld0ol0olKXXWdckldXdl0OldNMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMNk0WXk00dkO0NW0lxXWKkkxOXOdkO0N0dONKlkXxdkkOXkdOk0N0ONXkKXxxkx0WMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMWMWWWWMWWWWWWWWWWWWNNWWWWWNNNWWMMWWMWWWWWWMMWWWWWMMWMWWWWMWNWMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMWWWMMWMMMWWWWMMMMMMMMWMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMWWMM
        MMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMM
        MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMM
        MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 
        ";

        System.Console.WriteLine(Walt);
    }

    public static void MethCalcTxt()
    {
        string meth = "_________________Meth Calculator_________________";
        Console.Clear();
        Console.ForegroundColor = ConsoleColor.DarkCyan;
        System.Console.WriteLine(meth);
        Console.ResetColor();
    }
}